#use barseq-r4
.libPaths("/opt/conda/envs/barseq-r4//lib/R/library/")
library(tidyverse)
library(Matrix)
library(SingleCellExperiment)
library(Seurat)
library(MetaNeighbor)
library(gridExtra)
library(googlesheets4)
library(sctransform)
library(clustree)
library(viridis)
library(dplyr)
library(gplots)
library(readr)
library(pheatmap)
library(tidyr)
library(FNN)  
library(ggplot2)
library(patchwork)
library(plotly)
library(RColorBrewer)
library(stringr)
library(readxl)
library(digest)
library(proxy)
library(matrixStats)
library(reshape2)
library(htmlwidgets)
library(grid)
library(doParallel)
library(R.matlab)
library(VennDiagram)
library(NMF)
library(cowplot)
library(ggrepel)
library(limma)
library(edgeR)

# Conversion of BARseq MATLAB files to RDS files used downstream happens in capsule https://codeocean.allenneuraldynamics.org/capsule/6190503/tree [PK_BARseq_MAT-RDS_conversion]
# due to impossibility of mounting library(hdf5r) in the current environment build