# Setup: loaded at the start of every rendered script via a hidden knitr chunk.
# Do NOT load this in individual scripts — it is injected by the run script.

.libPaths("/opt/conda/envs/barseq-r4//lib/R/library/")

suppressPackageStartupMessages({
  library(tidyverse)
  library(Matrix)
  library(SingleCellExperiment)
  library(Seurat)
  library(MetaNeighbor)
  library(gridExtra)
  library(googlesheets4)
  library(sctransform)
  library(clustree)
  library(viridis)
  library(dplyr)
  library(gplots)
  library(readr)
  library(pheatmap)
  library(tidyr)
  library(FNN)
  library(ggplot2)
  library(patchwork)
  library(plotly)
  library(RColorBrewer)
  library(stringr)
  library(readxl)
  library(digest)
  library(proxy)
  library(matrixStats)
  library(reshape2)
  library(htmlwidgets)
  library(grid)
  library(doParallel)
  library(R.matlab)
  library(VennDiagram)
  library(NMF)
  library(cowplot)
  library(ggrepel)
  library(limma)
  library(edgeR)
  library(tibble)
})